<script>
  export default {
    name: 'Icon',

    props: {
      type: {
        type: String,
        required: true
      }
    }
  }
</script>

<template>
  <i class="aurora-icon" :data-type="type"></i>
</template>

<style lang="scss">
  @font-face {
    font-family: 'Entypo';
    src: url('../icons/icomoon.eot');
    src: url('../icons/icomoon.eot#iefix') format('embedded-opentype'),
      url('../icons/icomoon.ttf') format('truetype'),
      url('../icons/icomoon.woff') format('woff'),
      url('../icons/icomoon.svg#icomoon') format('svg');
    font-weight: normal;
    font-style: normal;
  }

  .aurora-icon {
    font-family: 'Entypo' !important;
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;

    &[data-type="add-to-list"]:before { content: "\e900"; }
    &[data-type="classic-computer"]:before { content: "\e901"; }
    &[data-type="controller-fast-backward"]:before { content: "\e902"; }
    &[data-type="creative-commons-attribution"]:before { content: "\e903"; }
    &[data-type="creative-commons-noderivs"]:before { content: "\e904"; }
    &[data-type="creative-commons-noncommercial-eu"]:before { content: "\e905"; }
    &[data-type="creative-commons-noncommercial-us"]:before { content: "\e906"; }
    &[data-type="creative-commons-public-domain"]:before { content: "\e907"; }
    &[data-type="creative-commons-remix"]:before { content: "\e908"; }
    &[data-type="creative-commons-share"]:before { content: "\e909"; }
    &[data-type="creative-commons-sharealike"]:before { content: "\e90a"; }
    &[data-type="creative-commons"]:before { content: "\e90b"; }
    &[data-type="document-landscape"]:before { content: "\e90c"; }
    &[data-type="remove-user"]:before { content: "\e90d"; }
    &[data-type="warning"]:before { content: "\e90e"; }
    &[data-type="arrow-bold-down"]:before { content: "\e90f"; }
    &[data-type="arrow-bold-left"]:before { content: "\e910"; }
    &[data-type="arrow-bold-right"]:before { content: "\e911"; }
    &[data-type="arrow-bold-up"]:before { content: "\e912"; }
    &[data-type="arrow-down"]:before { content: "\e913"; }
    &[data-type="arrow-left"]:before { content: "\e914"; }
    &[data-type="arrow-long-down"]:before { content: "\e915"; }
    &[data-type="arrow-long-left"]:before { content: "\e916"; }
    &[data-type="arrow-long-right"]:before { content: "\e917"; }
    &[data-type="arrow-long-up"]:before { content: "\e918"; }
    &[data-type="arrow-right"]:before { content: "\e919"; }
    &[data-type="arrow-up"]:before { content: "\e91a"; }
    &[data-type="arrow-with-circle-down"]:before { content: "\e91b"; }
    &[data-type="arrow-with-circle-left"]:before { content: "\e91c"; }
    &[data-type="arrow-with-circle-right"]:before { content: "\e91d"; }
    &[data-type="arrow-with-circle-up"]:before { content: "\e91e"; }
    &[data-type="bookmark"]:before { content: "\e91f"; }
    &[data-type="bookmarks"]:before { content: "\e920"; }
    &[data-type="chevron-down"]:before { content: "\e921"; }
    &[data-type="chevron-left"]:before { content: "\e922"; }
    &[data-type="chevron-right"]:before { content: "\e923"; }
    &[data-type="chevron-small-down"]:before { content: "\e924"; }
    &[data-type="chevron-small-left"]:before { content: "\e925"; }
    &[data-type="chevron-small-right"]:before { content: "\e926"; }
    &[data-type="chevron-small-up"]:before { content: "\e927"; }
    &[data-type="chevron-thin-down"]:before { content: "\e928"; }
    &[data-type="chevron-thin-left"]:before { content: "\e929"; }
    &[data-type="chevron-thin-right"]:before { content: "\e92a"; }
    &[data-type="chevron-thin-up"]:before { content: "\e92b"; }
    &[data-type="chevron-up"]:before { content: "\e92c"; }
    &[data-type="chevron-with-circle-down"]:before { content: "\e92d"; }
    &[data-type="chevron-with-circle-left"]:before { content: "\e92e"; }
    &[data-type="chevron-with-circle-right"]:before { content: "\e92f"; }
    &[data-type="chevron-with-circle-up"]:before { content: "\e930"; }
    &[data-type="cloud"]:before { content: "\e931"; }
    &[data-type="controller-fast-forward"]:before { content: "\e932"; }
    &[data-type="controller-jump-to-start"]:before { content: "\e933"; }
    &[data-type="controller-next"]:before { content: "\e934"; }
    &[data-type="controller-paus"]:before { content: "\e935"; }
    &[data-type="controller-play"]:before { content: "\e936"; }
    &[data-type="controller-record"]:before { content: "\e937"; }
    &[data-type="controller-stop"]:before { content: "\e938"; }
    &[data-type="controller-volume"]:before { content: "\e939"; }
    &[data-type="dot-single"]:before { content: "\e93a"; }
    &[data-type="dots-three-horizontal"]:before { content: "\e93b"; }
    &[data-type="dots-three-vertical"]:before { content: "\e93c"; }
    &[data-type="dots-two-horizontal"]:before { content: "\e93d"; }
    &[data-type="dots-two-vertical"]:before { content: "\e93e"; }
    &[data-type="download"]:before { content: "\e93f"; }
    &[data-type="emoji-flirt"]:before { content: "\e940"; }
    &[data-type="flow-branch"]:before { content: "\e941"; }
    &[data-type="flow-cascade"]:before { content: "\e942"; }
    &[data-type="flow-line"]:before { content: "\e943"; }
    &[data-type="flow-parallel"]:before { content: "\e944"; }
    &[data-type="flow-tree"]:before { content: "\e945"; }
    &[data-type="install"]:before { content: "\e946"; }
    &[data-type="layers"]:before { content: "\e947"; }
    &[data-type="open-book"]:before { content: "\e948"; }
    &[data-type="resize-100"]:before { content: "\e949"; }
    &[data-type="resize-full-screen"]:before { content: "\e94a"; }
    &[data-type="save"]:before { content: "\e94b"; }
    &[data-type="select-arrows"]:before { content: "\e94c"; }
    &[data-type="sound-mute"]:before { content: "\e94d"; }
    &[data-type="sound"]:before { content: "\e94e"; }
    &[data-type="trash"]:before { content: "\e94f"; }
    &[data-type="triangle-down"]:before { content: "\e950"; }
    &[data-type="triangle-left"]:before { content: "\e951"; }
    &[data-type="triangle-right"]:before { content: "\e952"; }
    &[data-type="triangle-up"]:before { content: "\e953"; }
    &[data-type="uninstall"]:before { content: "\e954"; }
    &[data-type="upload-to-cloud"]:before { content: "\e955"; }
    &[data-type="upload"]:before { content: "\e956"; }
    &[data-type="add-user"]:before { content: "\e957"; }
    &[data-type="address"]:before { content: "\e958"; }
    &[data-type="adjust"]:before { content: "\e959"; }
    &[data-type="air"]:before { content: "\e95a"; }
    &[data-type="aircraft-landing"]:before { content: "\e95b"; }
    &[data-type="aircraft-take-off"]:before { content: "\e95c"; }
    &[data-type="aircraft"]:before { content: "\e95d"; }
    &[data-type="align-bottom"]:before { content: "\e95e"; }
    &[data-type="align-horizontal-middle"]:before { content: "\e95f"; }
    &[data-type="align-left"]:before { content: "\e960"; }
    &[data-type="align-right"]:before { content: "\e961"; }
    &[data-type="align-top"]:before { content: "\e962"; }
    &[data-type="align-vertical-middle"]:before { content: "\e963"; }
    &[data-type="archive"]:before { content: "\e964"; }
    &[data-type="area-graph"]:before { content: "\e965"; }
    &[data-type="attachment"]:before { content: "\e966"; }
    &[data-type="awareness-ribbon"]:before { content: "\e967"; }
    &[data-type="back-in-time"]:before { content: "\e968"; }
    &[data-type="back"]:before { content: "\e969"; }
    &[data-type="bar-graph"]:before { content: "\e96a"; }
    &[data-type="battery"]:before { content: "\e96b"; }
    &[data-type="beamed-note"]:before { content: "\e96c"; }
    &[data-type="bell"]:before { content: "\e96d"; }
    &[data-type="blackboard"]:before { content: "\e96e"; }
    &[data-type="block"]:before { content: "\e96f"; }
    &[data-type="book"]:before { content: "\e970"; }
    &[data-type="bowl"]:before { content: "\e971"; }
    &[data-type="box"]:before { content: "\e972"; }
    &[data-type="briefcase"]:before { content: "\e973"; }
    &[data-type="browser"]:before { content: "\e974"; }
    &[data-type="brush"]:before { content: "\e975"; }
    &[data-type="bucket"]:before { content: "\e976"; }
    &[data-type="cake"]:before { content: "\e977"; }
    &[data-type="calculator"]:before { content: "\e978"; }
    &[data-type="calendar"]:before { content: "\e979"; }
    &[data-type="camera"]:before { content: "\e97a"; }
    &[data-type="ccw"]:before { content: "\e97b"; }
    &[data-type="chat"]:before { content: "\e97c"; }
    &[data-type="check"]:before { content: "\e97d"; }
    &[data-type="circle-with-cross"]:before { content: "\e97e"; }
    &[data-type="circle-with-minus"]:before { content: "\e97f"; }
    &[data-type="circle-with-plus"]:before { content: "\e980"; }
    &[data-type="circle"]:before { content: "\e981"; }
    &[data-type="circular-graph"]:before { content: "\e982"; }
    &[data-type="clapperboard"]:before { content: "\e983"; }
    &[data-type="clipboard"]:before { content: "\e984"; }
    &[data-type="clock"]:before { content: "\e985"; }
    &[data-type="code"]:before { content: "\e986"; }
    &[data-type="cog"]:before { content: "\e987"; }
    &[data-type="colours"]:before { content: "\e988"; }
    &[data-type="compass"]:before { content: "\e989"; }
    &[data-type="copy"]:before { content: "\e98a"; }
    &[data-type="credit-card"]:before { content: "\e98b"; }
    &[data-type="credit"]:before { content: "\e98c"; }
    &[data-type="cross"]:before { content: "\e98d"; }
    &[data-type="cup"]:before { content: "\e98e"; }
    &[data-type="cw"]:before { content: "\e98f"; }
    &[data-type="cycle"]:before { content: "\e990"; }
    &[data-type="database"]:before { content: "\e991"; }
    &[data-type="dial-pad"]:before { content: "\e992"; }
    &[data-type="direction"]:before { content: "\e993"; }
    &[data-type="document"]:before { content: "\e994"; }
    &[data-type="documents"]:before { content: "\e995"; }
    &[data-type="drink"]:before { content: "\e996"; }
    &[data-type="drive"]:before { content: "\e997"; }
    &[data-type="drop"]:before { content: "\e998"; }
    &[data-type="edit"]:before { content: "\e999"; }
    &[data-type="email"]:before { content: "\e99a"; }
    &[data-type="emoji-happy"]:before { content: "\e99b"; }
    &[data-type="emoji-neutral"]:before { content: "\e99c"; }
    &[data-type="emoji-sad"]:before { content: "\e99d"; }
    &[data-type="erase"]:before { content: "\e99e"; }
    &[data-type="eraser"]:before { content: "\e99f"; }
    &[data-type="export"]:before { content: "\e9a0"; }
    &[data-type="eye"]:before { content: "\e9a1"; }
    &[data-type="feather"]:before { content: "\e9a2"; }
    &[data-type="flag"]:before { content: "\e9a3"; }
    &[data-type="flash"]:before { content: "\e9a4"; }
    &[data-type="flashlight"]:before { content: "\e9a5"; }
    &[data-type="flat-brush"]:before { content: "\e9a6"; }
    &[data-type="folder-images"]:before { content: "\e9a7"; }
    &[data-type="folder-music"]:before { content: "\e9a8"; }
    &[data-type="folder-video"]:before { content: "\e9a9"; }
    &[data-type="folder"]:before { content: "\e9aa"; }
    &[data-type="forward"]:before { content: "\e9ab"; }
    &[data-type="funnel"]:before { content: "\e9ac"; }
    &[data-type="game-controller"]:before { content: "\e9ad"; }
    &[data-type="gauge"]:before { content: "\e9ae"; }
    &[data-type="globe"]:before { content: "\e9af"; }
    &[data-type="graduation-cap"]:before { content: "\e9b0"; }
    &[data-type="grid"]:before { content: "\e9b1"; }
    &[data-type="hair-cross"]:before { content: "\e9b2"; }
    &[data-type="hand"]:before { content: "\e9b3"; }
    &[data-type="heart-outlined"]:before { content: "\e9b4"; }
    &[data-type="heart"]:before { content: "\e9b5"; }
    &[data-type="help-with-circle"]:before { content: "\e9b6"; }
    &[data-type="help"]:before { content: "\e9b7"; }
    &[data-type="home"]:before { content: "\e9b8"; }
    &[data-type="hour-glass"]:before { content: "\e9b9"; }
    &[data-type="image-inverted"]:before { content: "\e9ba"; }
    &[data-type="image"]:before { content: "\e9bb"; }
    &[data-type="images"]:before { content: "\e9bc"; }
    &[data-type="inbox"]:before { content: "\e9bd"; }
    &[data-type="infinity"]:before { content: "\e9be"; }
    &[data-type="info-with-circle"]:before { content: "\e9bf"; }
    &[data-type="info"]:before { content: "\e9c0"; }
    &[data-type="key"]:before { content: "\e9c1"; }
    &[data-type="keyboard"]:before { content: "\e9c2"; }
    &[data-type="lab-flask"]:before { content: "\e9c3"; }
    &[data-type="landline"]:before { content: "\e9c4"; }
    &[data-type="language"]:before { content: "\e9c5"; }
    &[data-type="laptop"]:before { content: "\e9c6"; }
    &[data-type="leaf"]:before { content: "\e9c7"; }
    &[data-type="level-down"]:before { content: "\e9c8"; }
    &[data-type="level-up"]:before { content: "\e9c9"; }
    &[data-type="lifebuoy"]:before { content: "\e9ca"; }
    &[data-type="light-bulb"]:before { content: "\e9cb"; }
    &[data-type="light-down"]:before { content: "\e9cc"; }
    &[data-type="light-up"]:before { content: "\e9cd"; }
    &[data-type="line-graph"]:before { content: "\e9ce"; }
    &[data-type="link"]:before { content: "\e9cf"; }
    &[data-type="list"]:before { content: "\e9d0"; }
    &[data-type="location-pin"]:before { content: "\e9d1"; }
    &[data-type="location"]:before { content: "\e9d2"; }
    &[data-type="lock-open"]:before { content: "\e9d3"; }
    &[data-type="lock"]:before { content: "\e9d4"; }
    &[data-type="log-out"]:before { content: "\e9d5"; }
    &[data-type="login"]:before { content: "\e9d6"; }
    &[data-type="loop"]:before { content: "\e9d7"; }
    &[data-type="magnet"]:before { content: "\e9d8"; }
    &[data-type="magnifying-glass"]:before { content: "\e9d9"; }
    &[data-type="mail"]:before { content: "\e9da"; }
    &[data-type="man"]:before { content: "\e9db"; }
    &[data-type="map"]:before { content: "\e9dc"; }
    &[data-type="mask"]:before { content: "\e9dd"; }
    &[data-type="medal"]:before { content: "\e9de"; }
    &[data-type="megaphone"]:before { content: "\e9df"; }
    &[data-type="menu"]:before { content: "\e9e0"; }
    &[data-type="message"]:before { content: "\e9e1"; }
    &[data-type="mic"]:before { content: "\e9e2"; }
    &[data-type="minus"]:before { content: "\e9e3"; }
    &[data-type="mobile"]:before { content: "\e9e4"; }
    &[data-type="modern-mic"]:before { content: "\e9e5"; }
    &[data-type="moon"]:before { content: "\e9e6"; }
    &[data-type="mouse"]:before { content: "\e9e7"; }
    &[data-type="music"]:before { content: "\e9e8"; }
    &[data-type="network"]:before { content: "\e9e9"; }
    &[data-type="new-message"]:before { content: "\e9ea"; }
    &[data-type="new"]:before { content: "\e9eb"; }
    &[data-type="news"]:before { content: "\e9ec"; }
    &[data-type="note"]:before { content: "\e9ed"; }
    &[data-type="notification"]:before { content: "\e9ee"; }
    &[data-type="old-mobile"]:before { content: "\e9ef"; }
    &[data-type="old-phone"]:before { content: "\e9f0"; }
    &[data-type="palette"]:before { content: "\e9f1"; }
    &[data-type="paper-plane"]:before { content: "\e9f2"; }
    &[data-type="pencil"]:before { content: "\e9f3"; }
    &[data-type="phone"]:before { content: "\e9f4"; }
    &[data-type="pie-chart"]:before { content: "\e9f5"; }
    &[data-type="pin"]:before { content: "\e9f6"; }
    &[data-type="plus"]:before { content: "\e9f7"; }
    &[data-type="popup"]:before { content: "\e9f8"; }
    &[data-type="power-plug"]:before { content: "\e9f9"; }
    &[data-type="price-ribbon"]:before { content: "\e9fa"; }
    &[data-type="price-tag"]:before { content: "\e9fb"; }
    &[data-type="print"]:before { content: "\e9fc"; }
    &[data-type="progress-empty"]:before { content: "\e9fd"; }
    &[data-type="progress-full"]:before { content: "\e9fe"; }
    &[data-type="progress-one"]:before { content: "\e9ff"; }
    &[data-type="progress-two"]:before { content: "\ea00"; }
    &[data-type="publish"]:before { content: "\ea01"; }
    &[data-type="quote"]:before { content: "\ea02"; }
    &[data-type="radio"]:before { content: "\ea03"; }
    &[data-type="reply-all"]:before { content: "\ea04"; }
    &[data-type="reply"]:before { content: "\ea05"; }
    &[data-type="retweet"]:before { content: "\ea06"; }
    &[data-type="rocket"]:before { content: "\ea07"; }
    &[data-type="round-brush"]:before { content: "\ea08"; }
    &[data-type="rss"]:before { content: "\ea09"; }
    &[data-type="ruler"]:before { content: "\ea0a"; }
    &[data-type="scissors"]:before { content: "\ea0b"; }
    &[data-type="share-alternitive"]:before { content: "\ea0c"; }
    &[data-type="share"]:before { content: "\ea0d"; }
    &[data-type="shareable"]:before { content: "\ea0e"; }
    &[data-type="shield"]:before { content: "\ea0f"; }
    &[data-type="shop"]:before { content: "\ea10"; }
    &[data-type="shopping-bag"]:before { content: "\ea11"; }
    &[data-type="shopping-basket"]:before { content: "\ea12"; }
    &[data-type="shopping-cart"]:before { content: "\ea13"; }
    &[data-type="shuffle"]:before { content: "\ea14"; }
    &[data-type="signal"]:before { content: "\ea15"; }
    &[data-type="sound-mix"]:before { content: "\ea16"; }
    &[data-type="sports-club"]:before { content: "\ea17"; }
    &[data-type="spreadsheet"]:before { content: "\ea18"; }
    &[data-type="squared-cross"]:before { content: "\ea19"; }
    &[data-type="squared-minus"]:before { content: "\ea1a"; }
    &[data-type="squared-plus"]:before { content: "\ea1b"; }
    &[data-type="star-outlined"]:before { content: "\ea1c"; }
    &[data-type="star"]:before { content: "\ea1d"; }
    &[data-type="stopwatch"]:before { content: "\ea1e"; }
    &[data-type="suitcase"]:before { content: "\ea1f"; }
    &[data-type="swap"]:before { content: "\ea20"; }
    &[data-type="sweden"]:before { content: "\ea21"; }
    &[data-type="switch"]:before { content: "\ea22"; }
    &[data-type="tablet"]:before { content: "\ea23"; }
    &[data-type="tag"]:before { content: "\ea24"; }
    &[data-type="text-document-inverted"]:before { content: "\ea25"; }
    &[data-type="text-document"]:before { content: "\ea26"; }
    &[data-type="text"]:before { content: "\ea27"; }
    &[data-type="thermometer"]:before { content: "\ea28"; }
    &[data-type="thumbs-down"]:before { content: "\ea29"; }
    &[data-type="thumbs-up"]:before { content: "\ea2a"; }
    &[data-type="thunder-cloud"]:before { content: "\ea2b"; }
    &[data-type="ticket"]:before { content: "\ea2c"; }
    &[data-type="time-slot"]:before { content: "\ea2d"; }
    &[data-type="tools"]:before { content: "\ea2e"; }
    &[data-type="traffic-cone"]:before { content: "\ea2f"; }
    &[data-type="tree"]:before { content: "\ea30"; }
    &[data-type="trophy"]:before { content: "\ea31"; }
    &[data-type="tv"]:before { content: "\ea32"; }
    &[data-type="typing"]:before { content: "\ea33"; }
    &[data-type="unread"]:before { content: "\ea34"; }
    &[data-type="untag"]:before { content: "\ea35"; }
    &[data-type="user"]:before { content: "\ea36"; }
    &[data-type="users"]:before { content: "\ea37"; }
    &[data-type="v-card"]:before { content: "\ea38"; }
    &[data-type="video"]:before { content: "\ea39"; }
    &[data-type="vinyl"]:before { content: "\ea3a"; }
    &[data-type="voicemail"]:before { content: "\ea3b"; }
    &[data-type="wallet"]:before { content: "\ea3c"; }
    &[data-type="water"]:before { content: "\ea3d"; }
    &[data-type="500px-with-circle"]:before { content: "\ea3e"; }
    &[data-type="500px"]:before { content: "\ea3f"; }
    &[data-type="basecamp"]:before { content: "\ea40"; }
    &[data-type="behance"]:before { content: "\ea41"; }
    &[data-type="creative-cloud"]:before { content: "\ea42"; }
    &[data-type="dropbox"]:before { content: "\ea43"; }
    &[data-type="evernote"]:before { content: "\ea44"; }
    &[data-type="flattr"]:before { content: "\ea45"; }
    &[data-type="foursquare"]:before { content: "\ea46"; }
    &[data-type="google-drive"]:before { content: "\ea47"; }
    &[data-type="google-hangouts"]:before { content: "\ea48"; }
    &[data-type="grooveshark"]:before { content: "\ea49"; }
    &[data-type="icloud"]:before { content: "\ea4a"; }
    &[data-type="mixi"]:before { content: "\ea4b"; }
    &[data-type="onedrive"]:before { content: "\ea4c"; }
    &[data-type="paypal"]:before { content: "\ea4d"; }
    &[data-type="picasa"]:before { content: "\ea4e"; }
    &[data-type="qq"]:before { content: "\ea4f"; }
    &[data-type="rdio-with-circle"]:before { content: "\ea50"; }
    &[data-type="renren"]:before { content: "\ea51"; }
    &[data-type="scribd"]:before { content: "\ea52"; }
    &[data-type="sina-weibo"]:before { content: "\ea53"; }
    &[data-type="skype-with-circle"]:before { content: "\ea54"; }
    &[data-type="skype"]:before { content: "\ea55"; }
    &[data-type="slideshare"]:before { content: "\ea56"; }
    &[data-type="smashing"]:before { content: "\ea57"; }
    &[data-type="soundcloud"]:before { content: "\ea58"; }
    &[data-type="spotify-with-circle"]:before { content: "\ea59"; }
    &[data-type="spotify"]:before { content: "\ea5a"; }
    &[data-type="swarm"]:before { content: "\ea5b"; }
    &[data-type="vine-with-circle"]:before { content: "\ea5c"; }
    &[data-type="vine"]:before { content: "\ea5d"; }
    &[data-type="vk-alternitive"]:before { content: "\ea5e"; }
    &[data-type="vk-with-circle"]:before { content: "\ea5f"; }
    &[data-type="vk"]:before { content: "\ea60"; }
    &[data-type="xing-with-circle"]:before { content: "\ea61"; }
    &[data-type="xing"]:before { content: "\ea62"; }
    &[data-type="yelp"]:before { content: "\ea63"; }
    &[data-type="dribbble-with-circle"]:before { content: "\ea64"; }
    &[data-type="dribbble"]:before { content: "\ea65"; }
    &[data-type="facebook-with-circle"]:before { content: "\ea66"; }
    &[data-type="facebook"]:before { content: "\ea67"; }
    &[data-type="flickr-with-circle"]:before { content: "\ea68"; }
    &[data-type="flickr"]:before { content: "\ea69"; }
    &[data-type="github-with-circle"]:before { content: "\ea6a"; }
    &[data-type="github"]:before { content: "\ea6b"; }
    &[data-type="google-with-circle"]:before { content: "\ea6c"; }
    &[data-type="google"]:before { content: "\ea6d"; }
    &[data-type="instagram-with-circle"]:before { content: "\ea6e"; }
    &[data-type="instagram"]:before { content: "\ea6f"; }
    &[data-type="lastfm-with-circle"]:before { content: "\ea70"; }
    &[data-type="lastfm"]:before { content: "\ea71"; }
    &[data-type="linkedin-with-circle"]:before { content: "\ea72"; }
    &[data-type="linkedin"]:before { content: "\ea73"; }
    &[data-type="pinterest-with-circle"]:before { content: "\ea74"; }
    &[data-type="pinterest"]:before { content: "\ea75"; }
    &[data-type="rdio"]:before { content: "\ea76"; }
    &[data-type="stumbleupon-with-circle"]:before { content: "\ea77"; }
    &[data-type="stumbleupon"]:before { content: "\ea78"; }
    &[data-type="tumblr-with-circle"]:before { content: "\ea79"; }
    &[data-type="tumblr"]:before { content: "\ea7a"; }
    &[data-type="twitter-with-circle"]:before { content: "\ea7b"; }
    &[data-type="twitter"]:before { content: "\ea7c"; }
    &[data-type="vimeo-with-circle"]:before { content: "\ea7d"; }
    &[data-type="vimeo"]:before { content: "\ea7e"; }
    &[data-type="youtube-with-circle"]:before { content: "\ea7f"; }
    &[data-type="youtube"]:before { content: "\ea80"; }
  }
</style>